[profile.default]
src = "src"
out = "out"
libs = ["lib"]
[fuzz]
runs = 10000
remappings = ["@openzeppelin/=lib/openzeppelin-contracts/"]   # a list of remappings
#remappings = ["ds-test/=lib/forge-std/lib/ds-test/src/",
#"forge-std/=lib/forge-std/src/"]   # a list of remappings

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
